const audioMap = {
  "Ben Asya'nın ulu kağanı, Büyük Hun İmparatoru Mete Han! Yay çeken bütün kavimleri tek bir aile gibi birleştirdim. Soracakların varsa çekinme, söyle.": "./audio/metehan_greeting.mp3",
  "Ben Teoman'ın oğlu, Büyük Hun İmparatorluğu'nun en güçlü hükümdarı Mete Han'ım. M.Ö. 209'da tahta çıktım.": "./audio/metehan_dict_0.mp3",
  "Adım Mete'dir, bazıları bana Mao-tun der. Hun dilinde 'yiğit savaşçı' anlamına gelir.": "./audio/metehan_dict_1.mp3",
  "M.Ö. 234'te doğdum. M.Ö. 209'da tahta çıktım ve M.Ö. 174'te bu dünyadan göçtüm.": "./audio/metehan_dict_2.mp3",
  "M.Ö. 234 yılında, bozkırların ortasında doğdum. Bir kağanın oğlu olarak dünyaya geldim.": "./audio/metehan_dict_4.mp3",
  "M.Ö. 174 yılında öldüm. Ama kurduğum devlet yüzyıllarca yaşadı.": "./audio/metehan_dict_6.mp3",
  "Boyum hakkında kesin bir kayıt yoktur ama bir Türk kağanına yaraşır şekilde uzun boylu, geniş omuzlu ve iri yapılı bir savaşçıydım.": "./audio/metehan_dict_8.mp3",
  "Bir bozkır savaşçısı daima dinçtir. Kilom atımın beni rahatça taşıyabileceği, kılıcımı da güçlüce savurabileceğim kadardı.": "./audio/metehan_dict_10.mp3",
  "Geniş omuzlu, çelik gibi kaslara sahip, uykuyu sevmeyen, gözleri kartal gibi keskin bir kağandım.": "./audio/metehan_dict_11.mp3",
  "Babam Teoman, Hun İmparatorluğu'nun ilk büyük hükümdarıydı. Ama beni öldürtmek istedi, üvey annemin etkisiyle. Ben de ondan önce davrandım.": "./audio/metehan_dict_12.mp3",
  "Öz annem hakkında çok bilgi yoktur. Üvey annem babamı bana karşı kışkırttı. Babam beni Yüeçilere rehin olarak gönderdi ki ölmemi umuyordu.": "./audio/metehan_dict_13.mp3",
  "Babam Teoman beni rehin olarak düşmana verdi. Ama ben kaçtım ve geri döndüm. Tahta güçle çıktım.": "./audio/metehan_dict_14.mp3",
  "Hatunlarım vardı. Hun geleneğinde hatun, kağanın yanında devlet işlerinde söz sahibidir.": "./audio/metehan_dict_15.mp3",
  "Onlu sistemi ben kurdum. Ordumdaki onbaşılar, yüzbaşılar, binbaşılar ve tümenbaşılar bir makine gibi işler. Benim ıslık çalan okum nereye giderse, bütün ordum oraya ok atar!": "./audio/metehan_dict_16.mp3",
  "Onlu sistemi ben kurdum. 10 kişilik birliklerden başlayarak 10.000 kişilik tümenlere kadar hiyerarşik bir yapıdır. Bu sistem sayesinde 300.000 atlı süvariyi yönetebiliyordum.": "./audio/metehan_dict_17.mp3",
  "Benim her askerim at üstünde doğar, at üstünde savaşır. Bir Hun askeri hem okçu hem süvari hem de avcıdır. Çocukluktan itibaren ata binmeyi ve ok atmayı öğrenirler.": "./audio/metehan_dict_18.mp3",
  "Islık çalan ok benim icadımdır. Ben okumu nereye atarsam, askerlerim düşünmeden aynı hedefe ok atar. Tereddüt eden kellesini kaybeder. Sadakat ve disiplin her şeydir.": "./audio/metehan_dict_19.mp3",
  "Hayatım boyunca sayısız savaş kazandım. Doğuda Tunguzları, batıda Yüeçileri, kuzeyde Kırgızları ve güneyde Çin'i yendim. Tüm bozkırı birleştirdim.": "./audio/metehan_dict_20.mp3",
  "Kurt kapanı taktiğini biz icat ettik. Düşmanı sahte geri çekilmeyle tuzağa çeker, çember içine alırız. Bu taktik bin yıl sonra bile kullanılmıştır.": "./audio/metehan_dict_21.mp3",
  "At, Hun savaşçısının en değerli yoldaşıdır. Atsız Hun olmaz. Biz at üstünde doğar, at üstünde yaşar, at üstünde ölürüz.": "./audio/metehan_dict_22.mp3",
  "Ok ve yay bizim en önemli silahımızdır. Bir Hun atlı okçusu tam dörtnala koşarken arkasına dönüp ok atar. Buna Part atışı derler ama biz yüzyıllardır yapıyorduk.": "./audio/metehan_dict_23.mp3",
  "Kılıç, ok, yay, mızrak ve kement kullanırdık. Ama en güçlü silahımız disiplinli ordumuz ve süratimizdi.": "./audio/metehan_dict_24.mp3",
  "Vatan toprağı kutsaldır, asla terk edilemez! Toprak devletin temelidir, kimseye verilemez. Bir karış toprak bile verilemez!": "./audio/metehan_dict_25.mp3",
  "Toprak milletin malıdır! Toprak devletin temelidir, bir karış dahi olsa düşmana bırakılmaz. Bunu unutana kağan denmez.": "./audio/metehan_dict_26.mp3",
  "Çin'i yenmeme rağmen topraklarına girmedim, sadece vergiye bağladım. Çünkü nüfusumuz azdı, o kalabalık içinde asimile olabilirdik. Milletimin benliğini koruması her şeyden önemlidir.": "./audio/metehan_dict_27.mp3",
  "Turan, yay çeken tüm atlı göçebe kavimlerin birliğidir. Ben bu birliği sağladım. Moğolistan'dan Hazar'a kadar tek bayrak altında topladım.": "./audio/metehan_dict_28.mp3",
  "Biz Türk milletinin en eski ecdadıyız. Hun dili, Türk dilinin atasıdır. Bozkırda doğan bu millet, tarihi değiştirmiştir.": "./audio/metehan_dict_29.mp3",
  "Büyük Hun İmparatorluğu, Türk tarihinin ilk büyük devletidir. Ben bu devleti en geniş sınırlarına ulaştırdım. Çin Seddi bizim yüzümüzden inşa edilmiştir.": "./audio/metehan_dict_30.mp3",
  "Göktengri bizim en yüce inancımızdır. Gök Tanrı kağanı kutlu kılar ve millete güç verir. Biz Tengri'nin izniyle hükmederiz.": "./audio/metehan_dict_31.mp3",
  "Biz Gök Tanrı inancına bağlıyız. Tengri göklerin hâkimi, Yer-Su toprakların koruyucusudur. Kağan Tengri'nin yeryüzündeki gölgesidir.": "./audio/metehan_dict_32.mp3",
  "Bozkurt bizim kutsal atamızdır. Dişi kurt Asena, Türk milletini yeniden doğurmuştur. Kurt totemimiz güç, cesaret ve özgürlüğün simgesidir.": "./audio/metehan_dict_33.mp3",
  "Bozkır bizim vatanımızdır. Uçsuz bucaksız steplerde at koştururuz. Duvarlar ardında yaşamak bize göre değildir, biz özgür insanlarız.": "./audio/metehan_dict_34.mp3",
  "Biz et yeriz, kımız içeriz, süt ve peynir tüketiriz. Avcılık ve hayvancılık geçim kaynağımızdır. Toprak ekmek değildir, at sütü ve et yeter.": "./audio/metehan_dict_35.mp3",
  "Kımız, kısrak sütünden yapılır ve kutsal içeceğimizdir. Savaş öncesi askerlerime kımız dağıtırım, güç verir.": "./audio/metehan_dict_36.mp3",
  "Otağ dediğimiz çadırlarımız bizim evimizdir. Kolay kurulur, kolay taşınır. Bir Hun kağanının otağı altınla süslüdür.": "./audio/metehan_dict_37.mp3",
  "Devlet güçle kurulur, adaletle yaşatılır. Benim kurduğum onlu düzen, devlet yönetiminin de temelidir.": "./audio/metehan_dict_38.mp3",
  "Gerçek lider önden gider, askerlerinden fedakârlık istemeden önce kendisi yapar. Ben her savaşta en önde savaştım.": "./audio/metehan_dict_39.mp3",
  "Korkak adam kağan olamaz. Cesaret, Tengri'nin seçilmiş kullarına verdiği bir armağandır.": "./audio/metehan_dict_40.mp3",
  "Hun kadınları güçlü ve onurludur. Hatunlar devlet meclisinde söz sahibidir. Kadınsız bir ulus düşünülemez.": "./audio/metehan_dict_41.mp3",
  "Esenlikler dilerim. Ne öğrenmek istersin?": "./audio/metehan_dict_42.mp3",
  "Esenlikler! Kağanın huzurunda konuşabilirsin.": "./audio/metehan_dict_43.mp3",
  "Kutlu Tengri'nin izniyle gücümüz yerindedir. Sen nasılsın?": "./audio/metehan_dict_44.mp3",
  "Bir Hun kağanı teşekküre alışık değildir ama senin saygını takdir ederim.": "./audio/metehan_dict_45.mp3",
  "Tengri yolunu açık etsin. Esenlikle git.": "./audio/metehan_dict_46.mp3",
  "Yolun açık olsun savaşçı. Bozkırda tekrar buluşuruz.": "./audio/metehan_dict_47.mp3",
  "Bu konuda söyleyeceklerim kısadır, biz çok konuşmayı değil çok iş yapmayı severiz.": "./audio/metehan_default_0.mp3",
  "Sözlerin rüzgar gibi, ne dediğini tam anlayamadım. Başka bir şey sor.": "./audio/metehan_default_1.mp3",
  "Hun ordusunda disiplinden gayrı bir şey sorulmaz, başka bir sorun var mı?": "./audio/metehan_default_2.mp3",
  "At üstünde geçen bir ömürde bu sorduğun teferruattır.": "./audio/metehan_default_3.mp3",
  "Bozkırın bilgeliğiyle cevap vereyim: her soru cevabı hak etmez, ama sen sor bakalım.": "./audio/metehan_default_4.mp3",
  "Bu meseleyi düşünmem gerek. Başka bir konuda konuşalım.": "./audio/metehan_default_5.mp3",
  "Biz ki Konstantiniyye'yi fetheyleyen, iki kıtanın ve iki denizin hakimi Sultan Mehmed Han'ız! İlm-i siyasetten ve tarihten suallerini bekleriz.": "./audio/fatih_greeting.mp3",
  "Ben 7. Osmanlı Padişahı, Sultan II. Murad'ın oğlu Sultan Mehmed Han. 1453'te Konstantiniyye'yi fethederek 'Fatih' unvanını aldım ve bir çağı kapatıp yenisini açtım.": "./audio/fatih_dict_0.mp3",
  "Adım Mehmed'dir. Fatih unvanını İstanbul'u fethettikten sonra aldım. Avrupalılar bana 'Grand Turk' derler.": "./audio/fatih_dict_1.mp3",
  "30 Mart 1432'de Edirne'de doğdum. 3 Mayıs 1481'de 49 yaşında vefat ettim.": "./audio/fatih_dict_2.mp3",
  "30 Mart 1432'de Edirne'de, Sultan II. Murad'ın oğlu olarak dünyaya geldim.": "./audio/fatih_dict_4.mp3",
  "3 Mayıs 1481'de sefer esnasında vefat ettim. Bazıları zehirlendiğimi söyler. 49 yıllık ömrümde 25 sefere çıktım.": "./audio/fatih_dict_6.mp3",
  "Boyum orta uzunlukta, yaklaşık 1 metre 70 santimdi. Çevik ve heybetli bir yapım vardı.": "./audio/fatih_dict_8.mp3",
  "Gençliğimde at üstünde cenk edecek kadar zinde, ömrümün sonlarında ise gut hastalığının etkisiyle biraz daha kiloluydum.": "./audio/fatih_dict_10.mp3",
  "İtalyan ressam Bellini portremi çizdiğinde kemerli burnumu ve vakur duruşumu resmetmiştir. Padişahlık vakarı her halimizden belli olurdu.": "./audio/fatih_dict_11.mp3",
  "Babam Sultan II. Murad büyük bir hükümdardı. Tahtı bana iki kez bıraktı. İlkinde çok gençtim, tekrar geri döndü. İkincisinde artık hazırdım.": "./audio/fatih_dict_12.mp3",
  "Annem Hüma Hatun'dur. Beni ilim ve irfanla büyüttü.": "./audio/fatih_dict_13.mp3",
  "Babam II. Murad, oğullarım Bayezid ve Cem Sultan. Bayezid benden sonra tahta çıktı.": "./audio/fatih_dict_14.mp3",
  "Birden fazla hatunlarım oldu. Osmanlı hanedanında nikâh ve siyaset iç içedir.": "./audio/fatih_dict_15.mp3",
  "Ya ben İstanbul'u alırım, ya İstanbul beni! O şehri fethetmek, peygamberimizin müjdesine nail olmaktır. Gemileri karadan yürüttük, aşılmaz denilen surları yıktık.": "./audio/fatih_dict_16.mp3",
  "53 gün süren muhasaradan sonra 29 Mayıs 1453'te İstanbul'u fethettim. Bu fetihle Orta Çağ sona erdi, Yeni Çağ başladı. Tarih bunu böyle yazar.": "./audio/fatih_dict_17.mp3",
  "Konstantiniyye, Roma İmparatorluğu'nun son kalesi idi. Ben onu fethederek İslam'ın vaadini gerçekleştirdim ve şehrin adını İstanbul kıldım.": "./audio/fatih_dict_18.mp3",
  "İstanbul'un surları bin yıl boyunca aşılamamıştı. Ben şahi toplarıyla o surları yıktım. Teknoloji ve strateji birleşince aşılamaz denen her şey aşılır.": "./audio/fatih_dict_19.mp3",
  "Bizans Haliç'e zincir germişti. Çaresizlik bize göre değildir! Gecenin karanlığında gemileri karadan kızaklar üzerinden Haliç'e indirdik. Tarih böyle yazılır.": "./audio/fatih_dict_20.mp3",
  "Haliç'e geçiş zincirleme kapatılmıştı. 72 gemiyi kara üzerinden taşıyarak Haliç'e indirdik. Bizanslılar gözlerine inanamadı.": "./audio/fatih_dict_21.mp3",
  "Şahi toplarını döktürdüm. Surları yıkmak için mühendisliğin, bilimin kudretine inandım. Urban Usta ile bu kudreti inşa ettik.": "./audio/fatih_dict_22.mp3",
  "Macar top ustası Urban bize geldi. Ona dünyada eşi görülmemiş büyüklükte toplar döktürdüm. Şahi topu surları paramparça etti.": "./audio/fatih_dict_23.mp3",
  "Alimlerin atının ayağından sıçrayan çamur, bizim kaftanımızın süsüdür. Ali Kuşçu gibi, Akşemseddin gibi nice alimleri sarayımızda ağırladık.": "./audio/fatih_dict_24.mp3",
  "Ali Kuşçu büyük bir astronomi ve matematik alimidir. Fetihten sonra onu İstanbul'a davet ettim ve medreselerimizde ders verdirdim.": "./audio/fatih_dict_25.mp3",
  "Akşemseddin hocam, fetih sırasında manevi rehberimdi. Ebu Eyyub el-Ensari hazretlerinin kabrini o keşfetti.": "./audio/fatih_dict_26.mp3",
  "Doğunun ve Batının hükümdarıyım. İtalyan ressam Bellini'ye portremi çizdirdim, Yunanca, Latince, Arapça ve Farsça öğrendim.": "./audio/fatih_dict_27.mp3",
  "İtalyan ressam Gentile Bellini'yi sarayıma davet ettim ve portremi çizdirdim. Sanata ve güzelliğe değer veren bir hükümdarım.": "./audio/fatih_dict_28.mp3",
  "Türkçe, Arapça, Farsça, Yunanca, Latince ve İtalyanca bilirdim. Altı dil konuşan bir padişahtım. İlim dille öğrenilir.": "./audio/fatih_dict_29.mp3",
  "Kütüphanemde binlerce el yazması eser vardı. Batı ve Doğu felsefesini okudum. Aristoteles'i de Farabi'yi de bilirim.": "./audio/fatih_dict_30.mp3",
  "Fatih Kanunnamesi'ni ben yazdırdım. Devletin düzeni ve nizam-ı alem için kanun şarttır. Kardeş katlini de devletin bekası için koydum.": "./audio/fatih_dict_31.mp3",
  "Kanunnamemle devlet yönetimini sistematik hale getirdim. Her görevlinin yetki ve sorumlulukları açıkça belirlendi.": "./audio/fatih_dict_32.mp3",
  "Ordumda yeniçeriler, sipahiler, akıncılar ve topçular vardı. Dünyanın en modern ve disiplinli ordusuydu.": "./audio/fatih_dict_33.mp3",
  "Yeniçeriler seçkin piyade askerleriydi. Devşirme sistemiyle yetiştirilen bu askerler ölüme meydan okurdu.": "./audio/fatih_dict_34.mp3",
  "Güçlü bir donanma kurdum. Denizlerde de hâkim olmak istedim. Ege, Karadeniz ve Adriyatik'te donanmamız hüküm sürdü.": "./audio/fatih_dict_35.mp3",
  "25 sefere çıktım. İstanbul, Belgrad, Otranto, Trabzon, Mora, Bosna... Durmak yok, fetih var!": "./audio/fatih_dict_36.mp3",
  "Ayasofya'yı camiye çevirdim. O muhteşem kubbenin altında ilk namazı kıldığımda, tarihin ağırlığını hissettim.": "./audio/fatih_dict_37.mp3",
  "İstanbul'da pek çok cami yaptırdım. Fatih Camii bunların en büyüğüdür. İlim ve ibadet iç içedir.": "./audio/fatih_dict_38.mp3",
  "Sahn-ı Seman medreselerini kurdum. Sekiz büyük medrese ile İstanbul'u ilim merkezi yaptım.": "./audio/fatih_dict_39.mp3",
  "Topkapı Sarayı'nı ben yaptırdım. Dört yüz yıl boyunca Osmanlı'nın kalbi orada attı.": "./audio/fatih_dict_40.mp3",
  "Osmanlı Devleti benim dönemimde imparatorluk oldu. Üç kıtaya hükmeden bir cihan devleti kurduk.": "./audio/fatih_dict_41.mp3",
  "Adalet mülkün temelidir. Hükümdar adil olmazsa devlet ayakta duramaz.": "./audio/fatih_dict_42.mp3",
  "İslam'ın bayraktarıyız. Fetih, Allah'ın vaadinin gerçekleşmesidir. Ama gayrimüslimlere de adaletle davrandım.": "./audio/fatih_dict_43.mp3",
  "İstanbul'u fethettikten sonra Rum Patriğini makamında bıraktım. Dinlerini yaşamalarına izin verdim. Çünkü adalet böyle olur.": "./audio/fatih_dict_44.mp3",
  "Hoş geldin ademoğlu. İlme talip ol ki kıymetin artsın.": "./audio/fatih_dict_45.mp3",
  "Ve aleyküm selam. Huzurumuza hoş geldiniz.": "./audio/fatih_dict_46.mp3",
  "Devlet-i Aliyye'nin bekası için daima tetikte ve kudretliyiz. Sen nasılsın?": "./audio/fatih_dict_47.mp3",
  "Teşekkürün kabul olundu. Huzurumuzda edep ile konuş.": "./audio/fatih_dict_48.mp3",
  "Allah'a emanet ol. Yolun açık, kılıcın keskin olsun.": "./audio/fatih_dict_49.mp3",
  "Git, ilim öğren, sonra tekrar huzurumuza gel.": "./audio/fatih_dict_50.mp3",
  "Bu sualinin cevabını ulemaya danışmak icab eder.": "./audio/fatih_default_0.mp3",
  "Kılıcımızın ulaştığı yere, idrakınız ulaşamayabilir.": "./audio/fatih_default_1.mp3",
  "Bizim meselemiz nizam-ı alemdir, bu dediğin cüzi kalır.": "./audio/fatih_default_2.mp3",
  "Tarih, yaptıklarımızı yazar; sen ise sadece sorarsın. Başka bir sualin var mıdır?": "./audio/fatih_default_3.mp3",
  "Her suale cevap vermek padişahın vakarına yakışmaz, başka sor.": "./audio/fatih_default_4.mp3",
  "Bu mesele hakkında düşüncelerimiz mahfuzdur. Başka bir sual buyurun.": "./audio/fatih_default_5.mp3",
  "Benim naçiz vücudum elbet bir gün toprak olacaktır, ancak Türkiye Cumhuriyeti ilelebet payidar kalacaktır. Merhaba çocuk, bana sorularını sorabilirsin.": "./audio/ataturk_greeting.mp3",
  "Ben Mustafa Kemal Atatürk. Türkiye Cumhuriyeti'nin kurucusu ve ilk Cumhurbaşkanıyım. Hayatımı Türk milletinin bağımsızlığına ve çağdaşlaşmasına adadım.": "./audio/ataturk_dict_0.mp3",
  "Adım Mustafa'dır. Matematik öğretmenim Kemal ismini verdi. Soyadım Atatürk'tür, Türklerin Atası anlamına gelir.": "./audio/ataturk_dict_1.mp3",
  "1881'de Selanik'te doğdum. 10 Kasım 1938'de İstanbul'da hayata gözlerimi yumdum.": "./audio/ataturk_dict_2.mp3",
  "1881 yılında Selanik'te doğdum. O zamanlar Selanik Osmanlı toprağıydı.": "./audio/ataturk_dict_4.mp3",
  "10 Kasım 1938'de saat dokuzu beş geçe Dolmabahçe Sarayı'nda hayata gözlerimi yumdum. Siroz hastalığından vefat ettim.": "./audio/ataturk_dict_6.mp3",
  "Boyum 1 metre 74 santimdi. Ancak benim asıl büyüklüğüm fiziksel boyumda değil, milletime olan sevgimdedir.": "./audio/ataturk_dict_8.mp3",
  "Kilom genellikle 70 ile 74 civarındaydı. Ancak cepheden cepheye koşarken oldukça zayıfladığım dönemler de oldu.": "./audio/ataturk_dict_10.mp3",
  "Sarı saçlı, mavi gözlü, geniş omuzlu bir askerdim. Ancak en önemlisi, çelik gibi sağlam bir iradeye sahiptim.": "./audio/ataturk_dict_11.mp3",
  "Babam Ali Rıza Efendi, gümrük memuruydu. Eğitimime çok önem verdi. Beni askeri okula o yönlendirdi.": "./audio/ataturk_dict_12.mp3",
  "Annem Zübeyde Hanım, güçlü ve fedakâr bir Türk kadınıydı. Benim için dünyanın en değerli insanıydı.": "./audio/ataturk_dict_13.mp3",
  "Babam Ali Rıza Efendi, annem Zübeyde Hanım. Babamı küçük yaşta kaybettim. Annem beni büyük fedakârlıkla büyüttü.": "./audio/ataturk_dict_14.mp3",
  "Latife Hanım ile 1923'te evlendim. İki yıl sonra ayrıldık. Hayatımı milletim için yaşadım.": "./audio/ataturk_dict_15.mp3",
  "Selanik benim doğduğum şehirdir. Çocukluğum orada geçti. O şehir Balkan kültürlerinin buluşma noktasıydı.": "./audio/ataturk_dict_16.mp3",
  "Cumhuriyet, bilhassa kimsesizlerin kimsesidir. 29 Ekim 1923'te 'Egemenlik kayıtsız şartsız milletindir' ilkesiyle Cumhuriyeti ilan ettik.": "./audio/ataturk_dict_17.mp3",
  "Egemenlik kayıtsız şartsız milletindir. Hiçbir kişi, hiçbir aile, hiçbir sınıf milletin üstünde olamaz.": "./audio/ataturk_dict_18.mp3",
  "Türkiye Büyük Millet Meclisi'ni 23 Nisan 1920'de Ankara'da açtık. Milletin iradesi orada temsil edilir.": "./audio/ataturk_dict_19.mp3",
  "TBMM milletin kalesidir. 23 Nisan 1920'de kuruldu. Egemenliğin tek sahibi millettir ve onu Meclis temsil eder.": "./audio/ataturk_dict_20.mp3",
  "Ankara'yı başkent yaptık çünkü stratejik konumu uygundu ve Anadolu'nun kalbindeydi. Yeni bir devlet, yeni bir başkent.": "./audio/ataturk_dict_21.mp3",
  "Ey Türk gençliği! Birinci vazifen; Türk istiklalini, Türk cumhuriyetini, ilelebet muhafaza ve müdafaa etmektir. Bütün ümidim gençliktedir.": "./audio/ataturk_dict_22.mp3",
  "Dünyada her şey için, maddiyat için, maneviyat için, başarı için en hakiki mürşit ilimdir, fendir.": "./audio/ataturk_dict_23.mp3",
  "Eğitimdir ki bir milleti ya hür, bağımsız, şanlı, yüksek bir topluluk halinde yaşatır; ya da milleti esaret ve sefalete terk eder.": "./audio/ataturk_dict_24.mp3",
  "Milletleri kurtaranlar yalnız ve ancak öğretmenlerdir. Öğretmene hürmet, milletin geleceğine saygıdır.": "./audio/ataturk_dict_25.mp3",
  "1928'de Latin alfabesine geçtik. Harf Devrimi ile okuma yazma oranı hızla arttı. Milletimiz artık çağdaş dünya ile aynı dili konuşur.": "./audio/ataturk_dict_26.mp3",
  "Harf Devrimi çağdaşlaşmanın temel taşlarından biridir. Ben bizzat kara tahta başında milletimize yeni harfleri öğrettim.": "./audio/ataturk_dict_27.mp3",
  "Yurtta sulh, cihanda sulh! Bizim dış politikamızın ve insanlık anlayışımızın temelidir.": "./audio/ataturk_dict_28.mp3",
  "Ben size taarruzu emretmiyorum, ölmeyi emrediyorum! Çanakkale geçilmez dedik ve geçirmedik.": "./audio/ataturk_dict_29.mp3",
  "Kurtuluş Savaşı milletin var olma mücadelesiydi. Ya istiklal ya ölüm! Başka seçenek yoktu.": "./audio/ataturk_dict_30.mp3",
  "Savaş zorunlu olmadıkça cinayettir. Ama vatanı savunmak için savaşmak en kutsal görevdir.": "./audio/ataturk_dict_31.mp3",
  "Sakarya Meydan Muharebesi dönüm noktasıydı. 22 gün 22 gece sürdü. Hattı müdafaa yoktur, sathı müdafaa vardır! Sath, bütün vatandır.": "./audio/ataturk_dict_32.mp3",
  "Büyük Taarruz 26 Ağustos 1922'de başladı. Dumlupınar'da düşman ordusunu kesin olarak yenilgiye uğrattık. Ordular, ilk hedefiniz Akdeniz'dir. İleri!": "./audio/ataturk_dict_33.mp3",
  "Lozan Antlaşması 24 Temmuz 1923'te imzalandı. Bu antlaşmayla tam bağımsızlığımız tüm dünya tarafından tanındı.": "./audio/ataturk_dict_34.mp3",
  "Laiklik, din ve devlet işlerinin ayrılmasıdır. Din vicdan meselesidir, devlet akıl işidir. Her vatandaş inancında özgürdür.": "./audio/ataturk_dict_35.mp3",
  "Din vicdan meselesidir. Herkes vicdanının emrine uymakta serbesttir. Biz dine saygı gösteririz, din işlerini siyasete karıştırmayız.": "./audio/ataturk_dict_36.mp3",
  "Dünyada hiçbir milletin kadını, ben Anadolu kadınından daha fazla çalıştım diyemez. Kadın haklarını verdik çünkü kadınlarımız bunu çoktan hak etmişti.": "./audio/ataturk_dict_37.mp3",
  "İnkılaplarımız Türk milletini çağdaş medeniyet seviyesinin üstüne çıkarmak içindir. Kılık kıyafetten hukuka, takvimden eğitime kadar köklü değişiklikler yaptık.": "./audio/ataturk_dict_38.mp3",
  "Ne mutlu Türk'üm diyene! Türk milleti çalışkandır, zekidir. Yeter ki gerçek önderleri bulunsun.": "./audio/ataturk_dict_39.mp3",
  "Ne mutlu Türk'üm diyene! Türk milleti demokratik, laik ve sosyal bir hukuk devleti olarak ilelebet yaşayacaktır.": "./audio/ataturk_dict_40.mp3",
  "Tam bağımsızlık, ancak ekonomik bağımsızlıkla mümkündür. Siyasi ve askeri zaferler ekonomik zaferlerle taçlandırılmalıdır.": "./audio/ataturk_dict_41.mp3",
  "Ekonomik kalkınma her şeyin temelidir. Siyasi zaferler ne kadar büyük olursa olsun, ekonomik zaferlerle taçlandırılmazsa kazanılacak zaferler yaşayamaz.": "./audio/ataturk_dict_42.mp3",
  "Tarih yazmak, tarih yapmak kadar mühimdir. Yazan yapana sadık kalmazsa değişmeyen hakikat insanlığı şaşırtacak bir mahiyet alır.": "./audio/ataturk_dict_43.mp3",
  "Ben sporcunun zeki, çevik ve ahlaklısını severim. Sağlam kafa sağlam vücutta bulunur.": "./audio/ataturk_dict_44.mp3",
  "Dolmabahçe Sarayı'nda son günlerimi geçirdim. Saatteki 09:05, benim sonsuzluğa yolculuğumun saatidir.": "./audio/ataturk_dict_45.mp3",
  "Benim ebedi istirahatgâhım Ankara'daki Anıtkabir'dir. Milletimle birlikte orada huzur buluyorum.": "./audio/ataturk_dict_46.mp3",
  "Merhaba. Gözlerinde aydınlık yarınların ışığını görüyorum.": "./audio/ataturk_dict_47.mp3",
  "Selam genç! Senin gibi meraklı gençler bu milletin geleceğidir.": "./audio/ataturk_dict_48.mp3",
  "Milletim huzurlu ve güvendeyse, ben de iyiyim demektir.": "./audio/ataturk_dict_49.mp3",
  "Asıl ben milletimin her bir ferdine müteşekkirim.": "./audio/ataturk_dict_50.mp3",
  "Yolun açık olsun genç. Unutma, hayatta en hakiki mürşit ilimdir.": "./audio/ataturk_dict_51.mp3",
  "Sana bir ödevim var: oku, öğren ve bu milleti yükselt. Görüşürüz.": "./audio/ataturk_dict_52.mp3",
  "Meseleleri akıl ve bilim yoluyla çözmeliyiz. Bu konuyu da öyle düşün.": "./audio/ataturk_default_0.mp3",
  "Geleceğin büyükleri olarak bu konularda daha derin araştırmalar yapmalısınız.": "./audio/ataturk_default_1.mp3",
  "Önemli olan çalışmak ve üretmektir. Başka bir sorun var mı?": "./audio/ataturk_default_2.mp3",
  "Bu meseleyi milletin iradesi ve çağdaş medeniyetler seviyesi çerçevesinde değerlendirmek gerekir.": "./audio/ataturk_default_3.mp3",
  "Her konuda bilimin rehberliğine başvurmalıyız. Başka ne sormak istersin?": "./audio/ataturk_default_4.mp3",
  "Bu konu hakkında düşüncelerimi paylaşmam zor, ama sen araştırmaya devam et.": "./audio/ataturk_default_5.mp3"
};
